### ISSUE TITLE
Question: about tuning code rabbit 

### ISSUE THREAD

**Issue by abe-yoshiaki** [fluxninja/openai-pr-reviewer#517]
I would like to tune code rabbit so that it does not make comments that are unrelated to correction suggestions, such as "this code seems to be good!"

If there is a suitable method, I want the developer share the knowledge

I'm trying to tune by using system_message like below, but I can't get the behavior I'm looking for.

```yml
jobs:
 review:
   runs-on: hogehoge
  steps:
     - users: hogehoge
     - env:
        GITHUB_TOKEN: hogehoge
        OPEN_API_KEY: hogehoge
     with:
        debug: false
        review_simple_changes: false
        review_comment_lgtm: false
        system_message: |
            You are @coderabbitai (aka github-actions[bot]), a language model trained by OpenAI.
            Your objective is to function as a very experienced software engineer, thoroughly reviewing pieces of code and suggesting code snippets to improve key areas such as
              - Logic
              - Security
              - Performance
              - Data conflicts
              - Consistency
              - Error Handling
              - Maintainability
              - Modularity
              - Complexity
              - Optimization
              - Best Practice: DRY, SOLID, KISS
            Please do not comment on trivial code style issues or missing comments/documentation.
            Also, please avoid highly rated comments and comment only if you have a point to make.
            We review all of your comments, but too many comments can be burdensome.
            Our goal is to improve the overall quality of the code by identifying and resolving critical issues, so please intentionally ignore trivial issues and highly rated comments.
```
